In [32]:
import pandas as pd
from pathlib import Path

In [33]:
folder = Path(
    "/Users/dhairyajoshi/Public/iitgn assignments/Assignment 1 Kalpa- Healthcare/Week_3_Build_Week_Kalpa_Heath_Project/datapack/bookings/nova/combined"
)

# Get all JSONL files in the folder
files = list(folder.glob("*.jsonl"))

print("Files found:", len(files))

# Read and combine all files
chennai_nova_df = pd.concat(
    [pd.read_json(file, lines=True) for file in files],
    ignore_index=True
)

chennai_nova_df.head()

Files found: 6

,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient,tests,home_fee,rescheduled_from,status_at_export
0,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,"{'patient_id': 'PCHE0047415', 'is_new': False}","[{'code': 'T011', 'price': 750}, {'code': 'T01...",0,NaN,booked
1,nova_che_0099368,2026-06-17 22:53:00+05:30,2026-06-21 08:23:00+05:30,Chennai,CHE-01,CLINIC,APP,"{'patient_id': 'PCHE0022985', 'is_new': False}","[{'code': 'T009', 'price': 800}]",0,NaN,booked
2,nova_che_0099369,2026-06-04 10:51:00+05:30,2026-06-06 12:34:00+05:30,Chennai,CHE-02,CLINIC,PHONE,"{'patient_id': 'PCHE0050893', 'is_new': False}","[{'code': 'T014', 'price': 150}, {'code': 'T00...",0,NaN,booked
3,nova_che_0099370,2026-06-26 07:04:00+05:30,2026-06-28 10:53:00+05:30,Chennai,CHE-02,HOME,PHONE,"{'patient_id': 'PCHE0048337', 'is_new': False}","[{'code': 'PK01', 'price': 1499}, {'code': 'PK...",150,NaN,booked
4,nova_che_0099371,2026-06-06 00:56:00+05:30,2026-06-07 06:44:00+05:30,Chennai,CHE-04,CLINIC,APP,"{'patient_id': 'PCHE0047986', 'is_new': False}","[{'code': 'T008', 'price': 1100}, {'code': 'T0...",0,NaN,booked

In [34]:
chennai_nova_df.shape

(26543, 12)

In [35]:
chennai_nova_df[['patient_id', 'is_new']] = pd.DataFrame(chennai_nova_df['patient'].tolist(), index=chennai_nova_df.index)
chennai_nova_df

,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient,tests,home_fee,rescheduled_from,status_at_export,patient_id,is_new
0,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,"{'patient_id': 'PCHE0047415', 'is_new': False}","[{'code': 'T011', 'price': 750}, {'code': 'T01...",0,NaN,booked,PCHE0047415,False
1,nova_che_0099368,2026-06-17 22:53:00+05:30,2026-06-21 08:23:00+05:30,Chennai,CHE-01,CLINIC,APP,"{'patient_id': 'PCHE0022985', 'is_new': False}","[{'code': 'T009', 'price': 800}]",0,NaN,booked,PCHE0022985,False
2,nova_che_0099369,2026-06-04 10:51:00+05:30,2026-06-06 12:34:00+05:30,Chennai,CHE-02,CLINIC,PHONE,"{'patient_id': 'PCHE0050893', 'is_new': False}","[{'code': 'T014', 'price': 150}, {'code': 'T00...",0,NaN,booked,PCHE0050893,False
3,nova_che_0099370,2026-06-26 07:04:00+05:30,2026-06-28 10:53:00+05:30,Chennai,CHE-02,HOME,PHONE,"{'patient_id': 'PCHE0048337', 'is_new': False}","[{'code': 'PK01', 'price': 1499}, {'code': 'PK...",150,NaN,booked,PCHE0048337,False
4,nova_che_0099371,2026-06-06 00:56:00+05:30,2026-06-07 06:44:00+05:30,Chennai,CHE-04,CLINIC,APP,"{'patient_id': 'PCHE0047986', 'is_new': False}","[{'code': 'T008', 'price': 1100}, {'code': 'T0...",0,NaN,booked,PCHE0047986,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26538,nova_jai_0052704,2026-05-04 10:06:00+05:30,2026-05-09 19:27:00+05:30,Jaipur,JAI-01,CLINIC,PHONE,"{'patient_id': 'PJAI0020725', 'is_new': False}","[{'code': 'T005', 'price': 700}, {'code': 'PK0...",0,nova_jai_0051374,booked,PJAI0020725,False
26539,nova_jai_0052705,2026-05-03 06:27:00+05:30,2026-05-05 12:22:00+05:30,Jaipur,JAI-04,HOME,WALKIN,"{'patient_id': 'PJAI0003149', 'is_new': False}","[{'code': 'T018', 'price': 700}, {'code': 'T00...",150,nova_jai_0050258,booked,PJAI0003149,False
26540,nova_jai_0052706,2026-05-18 03:22:00+05:30,2026-05-26 11:13:00+05:30,Jaipur,JAI-03,CLINIC,WALKIN,"{'patient_id': 'PJAI0027519', 'is_new': False}","[{'code': 'T007', 'price': 550}]",0,nova_jai_0051827,booked,PJAI0027519,False
26541,nova_jai_0052707,2026-05-18 08:37:00+05:30,2026-05-22 16:27:00+05:30,Jaipur,JAI-04,CLINIC,APP,"{'patient_id': 'PJAI0026829', 'is_new': False}","[{'code': 'PK03', 'price': 999}, {'code': 'T00...",0,nova_jai_0051100,booked,PJAI0026829,False
26542,nova_jai_0052708,2026-05-11 00:33:00+05:30,2026-05-15 10:23:00+05:30,Jaipur,JAI-01,HOME,PHONE,"{'patient_id': 'PJAI0028547', 'is_new': True}","[{'code': 'T004', 'price': 650}]",150,nova_jai_0052139,booked,PJAI0028547,True

Using the explode function to separate the tests per booking. the resulting dataframe returns one row per test.

In [36]:
tests_df = chennai_nova_df.explode('tests', ignore_index=True)

In [37]:
tests_df

,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient,tests,home_fee,rescheduled_from,status_at_export,patient_id,is_new
0,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,"{'patient_id': 'PCHE0047415', 'is_new': False}","{'code': 'T011', 'price': 750}",0,NaN,booked,PCHE0047415,False
1,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,"{'patient_id': 'PCHE0047415', 'is_new': False}","{'code': 'T012', 'price': 600}",0,NaN,booked,PCHE0047415,False
2,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,"{'patient_id': 'PCHE0047415', 'is_new': False}","{'code': 'PK04', 'price': 2499}",0,NaN,booked,PCHE0047415,False
3,nova_che_0099368,2026-06-17 22:53:00+05:30,2026-06-21 08:23:00+05:30,Chennai,CHE-01,CLINIC,APP,"{'patient_id': 'PCHE0022985', 'is_new': False}","{'code': 'T009', 'price': 800}",0,NaN,booked,PCHE0022985,False
4,nova_che_0099369,2026-06-04 10:51:00+05:30,2026-06-06 12:34:00+05:30,Chennai,CHE-02,CLINIC,PHONE,"{'patient_id': 'PCHE0050893', 'is_new': False}","{'code': 'T014', 'price': 150}",0,NaN,booked,PCHE0050893,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62434,nova_jai_0052705,2026-05-03 06:27:00+05:30,2026-05-05 12:22:00+05:30,Jaipur,JAI-04,HOME,WALKIN,"{'patient_id': 'PJAI0003149', 'is_new': False}","{'code': 'T002', 'price': 120}",150,nova_jai_0050258,booked,PJAI0003149,False
62435,nova_jai_0052706,2026-05-18 03:22:00+05:30,2026-05-26 11:13:00+05:30,Jaipur,JAI-03,CLINIC,WALKIN,"{'patient_id': 'PJAI0027519', 'is_new': False}","{'code': 'T007', 'price': 550}",0,nova_jai_0051827,booked,PJAI0027519,False
62436,nova_jai_0052707,2026-05-18 08:37:00+05:30,2026-05-22 16:27:00+05:30,Jaipur,JAI-04,CLINIC,APP,"{'patient_id': 'PJAI0026829', 'is_new': False}","{'code': 'PK03', 'price': 999}",0,nova_jai_0051100,booked,PJAI0026829,False
62437,nova_jai_0052707,2026-05-18 08:37:00+05:30,2026-05-22 16:27:00+05:30,Jaipur,JAI-04,CLINIC,APP,"{'patient_id': 'PJAI0026829', 'is_new': False}","{'code': 'T001', 'price': 350}",0,nova_jai_0051100,booked,PJAI0026829,False
62438,nova_jai_0052708,2026-05-11 00:33:00+05:30,2026-05-15 10:23:00+05:30,Jaipur,JAI-01,HOME,PHONE,"{'patient_id': 'PJAI0028547', 'is_new': True}","{'code': 'T004', 'price': 650}",150,nova_jai_0052139,booked,PJAI0028547,True

In [38]:
detailed_tests = pd.json_normalize(tests_df['tests'])

In [39]:
detailed_tests.head()

   code   price
0  T011   750.0
1  T012   600.0
2  PK04  2499.0
3  T009   800.0
4  T014   150.0

In [40]:
tests_df = (
    tests_df
    .drop(columns='tests')
    .join(detailed_tests)
)

In [41]:
tests_df.head()

,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient,home_fee,rescheduled_from,status_at_export,patient_id,is_new,code,price
0,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,"{'patient_id': 'PCHE0047415', 'is_new': False}",0,NaN,booked,PCHE0047415,False,T011,750.0
1,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,"{'patient_id': 'PCHE0047415', 'is_new': False}",0,NaN,booked,PCHE0047415,False,T012,600.0
2,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,"{'patient_id': 'PCHE0047415', 'is_new': False}",0,NaN,booked,PCHE0047415,False,PK04,2499.0
3,nova_che_0099368,2026-06-17 22:53:00+05:30,2026-06-21 08:23:00+05:30,Chennai,CHE-01,CLINIC,APP,"{'patient_id': 'PCHE0022985', 'is_new': False}",0,NaN,booked,PCHE0022985,False,T009,800.0
4,nova_che_0099369,2026-06-04 10:51:00+05:30,2026-06-06 12:34:00+05:30,Chennai,CHE-02,CLINIC,PHONE,"{'patient_id': 'PCHE0050893', 'is_new': False}",0,NaN,booked,PCHE0050893,False,T014,150.0

In [42]:
tests_df = (tests_df.drop(columns = 'patient'))
tests_df

,booking_id,created_at,slot_at,city,clinic_id,channel,source,home_fee,rescheduled_from,status_at_export,patient_id,is_new,code,price
0,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,0,NaN,booked,PCHE0047415,False,T011,750.0
1,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,0,NaN,booked,PCHE0047415,False,T012,600.0
2,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,0,NaN,booked,PCHE0047415,False,PK04,2499.0
3,nova_che_0099368,2026-06-17 22:53:00+05:30,2026-06-21 08:23:00+05:30,Chennai,CHE-01,CLINIC,APP,0,NaN,booked,PCHE0022985,False,T009,800.0
4,nova_che_0099369,2026-06-04 10:51:00+05:30,2026-06-06 12:34:00+05:30,Chennai,CHE-02,CLINIC,PHONE,0,NaN,booked,PCHE0050893,False,T014,150.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62434,nova_jai_0052705,2026-05-03 06:27:00+05:30,2026-05-05 12:22:00+05:30,Jaipur,JAI-04,HOME,WALKIN,150,nova_jai_0050258,booked,PJAI0003149,False,T002,120.0
62435,nova_jai_0052706,2026-05-18 03:22:00+05:30,2026-05-26 11:13:00+05:30,Jaipur,JAI-03,CLINIC,WALKIN,0,nova_jai_0051827,booked,PJAI0027519,False,T007,550.0
62436,nova_jai_0052707,2026-05-18 08:37:00+05:30,2026-05-22 16:27:00+05:30,Jaipur,JAI-04,CLINIC,APP,0,nova_jai_0051100,booked,PJAI0026829,False,PK03,999.0
62437,nova_jai_0052707,2026-05-18 08:37:00+05:30,2026-05-22 16:27:00+05:30,Jaipur,JAI-04,CLINIC,APP,0,nova_jai_0051100,booked,PJAI0026829,False,T001,350.0
62438,nova_jai_0052708,2026-05-11 00:33:00+05:30,2026-05-15 10:23:00+05:30,Jaipur,JAI-01,HOME,PHONE,150,nova_jai_0052139,booked,PJAI0028547,True,T004,650.0

In [43]:
tests_df.to_csv('chennai_nova_bookings.csv', index=False)

In [44]:
tests_new = tests_df.rename(columns={'code': 'test_code', 'price': 'test_price'})

In [45]:
tests_new.head()

,booking_id,created_at,slot_at,city,clinic_id,channel,source,home_fee,rescheduled_from,status_at_export,patient_id,is_new,test_code,test_price
0,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,0,NaN,booked,PCHE0047415,False,T011,750.0
1,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,0,NaN,booked,PCHE0047415,False,T012,600.0
2,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,0,NaN,booked,PCHE0047415,False,PK04,2499.0
3,nova_che_0099368,2026-06-17 22:53:00+05:30,2026-06-21 08:23:00+05:30,Chennai,CHE-01,CLINIC,APP,0,NaN,booked,PCHE0022985,False,T009,800.0
4,nova_che_0099369,2026-06-04 10:51:00+05:30,2026-06-06 12:34:00+05:30,Chennai,CHE-02,CLINIC,PHONE,0,NaN,booked,PCHE0050893,False,T014,150.0

In [46]:
print(tests_new.columns.tolist())

['booking_id', 'created_at', 'slot_at', 'city', 'clinic_id', 'channel', 'source', 'home_fee', 'rescheduled_from', 'status_at_export', 'patient_id', 'is_new', 'test_code', 'test_price']

In [47]:
tests_new = tests_new[['booking_id', 'created_at', 'slot_at', 'city', 'clinic_id', 'channel', 'source', 'patient_id', 'test_code', 'test_price', 'home_fee']]

In [48]:
tests_new

,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,test_code,test_price,home_fee
0,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,PCHE0047415,T011,750.0,0
1,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,PCHE0047415,T012,600.0,0
2,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,PCHE0047415,PK04,2499.0,0
3,nova_che_0099368,2026-06-17 22:53:00+05:30,2026-06-21 08:23:00+05:30,Chennai,CHE-01,CLINIC,APP,PCHE0022985,T009,800.0,0
4,nova_che_0099369,2026-06-04 10:51:00+05:30,2026-06-06 12:34:00+05:30,Chennai,CHE-02,CLINIC,PHONE,PCHE0050893,T014,150.0,0
...,...,...,...,...,...,...,...,...,...,...,...
62434,nova_jai_0052705,2026-05-03 06:27:00+05:30,2026-05-05 12:22:00+05:30,Jaipur,JAI-04,HOME,WALKIN,PJAI0003149,T002,120.0,150
62435,nova_jai_0052706,2026-05-18 03:22:00+05:30,2026-05-26 11:13:00+05:30,Jaipur,JAI-03,CLINIC,WALKIN,PJAI0027519,T007,550.0,0
62436,nova_jai_0052707,2026-05-18 08:37:00+05:30,2026-05-22 16:27:00+05:30,Jaipur,JAI-04,CLINIC,APP,PJAI0026829,PK03,999.0,0
62437,nova_jai_0052707,2026-05-18 08:37:00+05:30,2026-05-22 16:27:00+05:30,Jaipur,JAI-04,CLINIC,APP,PJAI0026829,T001,350.0,0
62438,nova_jai_0052708,2026-05-11 00:33:00+05:30,2026-05-15 10:23:00+05:30,Jaipur,JAI-01,HOME,PHONE,PJAI0028547,T004,650.0,150

In [49]:
patients_df = pd.read_csv('/Users/dhairyajoshi/Public/iitgn assignments/Assignment 1 Kalpa- Healthcare/Week_3_Build_Week_Kalpa_Heath_Project/datapack/extracted_csv/patients/patients.csv')
patients_df

,patient_id,patient_name,phone,dob,city,signup_date
0,PAHM0030088,Rahul Fernandes,+91 85778 98441,1988-02-02,Ahmedabad,2023-01-14
1,PAHM0043743,Ananya D'Souza,+91 84824 41827,1992-11-13,Ahmedabad,2025-10-02
2,PAHM0011366,Rohan Mehta,+91 77327 81379,1944-07-05,Ahmedabad,2023-01-18
3,PAHM0009021,Vihaan Pillai,+91 76067 53849,1958-03-06,Ahmedabad,2022-08-06
4,PAHM0052680,Meera Desai,+91 81849 12697,2005-11-01,Ahmedabad,2026-05-19
...,...,...,...,...,...,...
309212,PPUN0034141,Ananya Shah,+91 72322 72862,1999-07-07,Pune,2025-09-09
309213,PPUN0013928,Siddharth Menon,+91 72309 39949,1967-03-30,Pune,2023-03-22
309214,PPUN0000920,Ritika Bose,+91 77049 50138,1969-09-16,Pune,2024-12-24
309215,PPUN0038468,Aditi Sharma,+91 83440 39856,2004-08-15,Pune,2026-02-28
309216,PPUN0010743,Nisha Fernandes,+91 76641 67964,1991-03-25,Pune,2024-11-27

In [50]:
tests_new = tests_new.merge(
    patients_df[['patient_id', 'patient_name']],
    on='patient_id',
    how='left'
)

In [51]:
tests_new

,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,test_code,test_price,home_fee,patient_name
0,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,PCHE0047415,T011,750.0,0,Rohan Patel
1,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,PCHE0047415,T012,600.0,0,Rohan Patel
2,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,PCHE0047415,PK04,2499.0,0,Rohan Patel
3,nova_che_0099368,2026-06-17 22:53:00+05:30,2026-06-21 08:23:00+05:30,Chennai,CHE-01,CLINIC,APP,PCHE0022985,T009,800.0,0,Ananya Bose
4,nova_che_0099369,2026-06-04 10:51:00+05:30,2026-06-06 12:34:00+05:30,Chennai,CHE-02,CLINIC,PHONE,PCHE0050893,T014,150.0,0,Vihaan Menon
...,...,...,...,...,...,...,...,...,...,...,...,...
62434,nova_jai_0052705,2026-05-03 06:27:00+05:30,2026-05-05 12:22:00+05:30,Jaipur,JAI-04,HOME,WALKIN,PJAI0003149,T002,120.0,150,Ananya Fernandes
62435,nova_jai_0052706,2026-05-18 03:22:00+05:30,2026-05-26 11:13:00+05:30,Jaipur,JAI-03,CLINIC,WALKIN,PJAI0027519,T007,550.0,0,Nisha Gupta
62436,nova_jai_0052707,2026-05-18 08:37:00+05:30,2026-05-22 16:27:00+05:30,Jaipur,JAI-04,CLINIC,APP,PJAI0026829,PK03,999.0,0,Neha Patel
62437,nova_jai_0052707,2026-05-18 08:37:00+05:30,2026-05-22 16:27:00+05:30,Jaipur,JAI-04,CLINIC,APP,PJAI0026829,T001,350.0,0,Neha Patel
62438,nova_jai_0052708,2026-05-11 00:33:00+05:30,2026-05-15 10:23:00+05:30,Jaipur,JAI-01,HOME,PHONE,PJAI0028547,T004,650.0,150,Arjun Joshi

In [52]:
tests_new = tests_new[['booking_id', 'created_at', 'slot_at', 'city', 'clinic_id', 'channel', 'source', 'patient_id','patient_name', 'test_code', 'test_price', 'home_fee']]

In [53]:
tests_new

,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee
0,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,PCHE0047415,Rohan Patel,T011,750.0,0
1,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,PCHE0047415,Rohan Patel,T012,600.0,0
2,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,PCHE0047415,Rohan Patel,PK04,2499.0,0
3,nova_che_0099368,2026-06-17 22:53:00+05:30,2026-06-21 08:23:00+05:30,Chennai,CHE-01,CLINIC,APP,PCHE0022985,Ananya Bose,T009,800.0,0
4,nova_che_0099369,2026-06-04 10:51:00+05:30,2026-06-06 12:34:00+05:30,Chennai,CHE-02,CLINIC,PHONE,PCHE0050893,Vihaan Menon,T014,150.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
62434,nova_jai_0052705,2026-05-03 06:27:00+05:30,2026-05-05 12:22:00+05:30,Jaipur,JAI-04,HOME,WALKIN,PJAI0003149,Ananya Fernandes,T002,120.0,150
62435,nova_jai_0052706,2026-05-18 03:22:00+05:30,2026-05-26 11:13:00+05:30,Jaipur,JAI-03,CLINIC,WALKIN,PJAI0027519,Nisha Gupta,T007,550.0,0
62436,nova_jai_0052707,2026-05-18 08:37:00+05:30,2026-05-22 16:27:00+05:30,Jaipur,JAI-04,CLINIC,APP,PJAI0026829,Neha Patel,PK03,999.0,0
62437,nova_jai_0052707,2026-05-18 08:37:00+05:30,2026-05-22 16:27:00+05:30,Jaipur,JAI-04,CLINIC,APP,PJAI0026829,Neha Patel,T001,350.0,0
62438,nova_jai_0052708,2026-05-11 00:33:00+05:30,2026-05-15 10:23:00+05:30,Jaipur,JAI-01,HOME,PHONE,PJAI0028547,Arjun Joshi,T004,650.0,150

In [54]:
tests_new.to_csv('Chennai_nova.csv', index = False)

In [55]:
df_chennai = pd.read_csv('Chennai_nova.csv')

In [56]:
df_chennai.shape

(62439, 12)

In [57]:
folder = Path("/Users/dhairyajoshi/Public/iitgn assignments/Assignment 1 Kalpa- Healthcare/Week_3_Build_Week_Kalpa_Heath_Project/datapack/bookings/nova/jaipur"
    
)

# Get all JSONL files in the folder
files = list(folder.glob("*.jsonl"))

print("Files found:", len(files))

# Read and combine all files
jaipur_nova_df = pd.concat(
    [pd.read_json(file, lines=True) for file in files],
    ignore_index=True
)

jaipur_nova_df.head()

Files found: 3

,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient,tests,home_fee,rescheduled_from,status_at_export
0,nova_jai_0052709,2026-06-26 03:04:00+05:30,2026-06-29 10:24:00+05:30,Jaipur,JAI-01,CLINIC,PHONE,"{'patient_id': 'PJAI0028832', 'is_new': False}","[{'code': 'T013', 'price': 400}, {'code': 'T00...",0,NaN,booked
1,nova_jai_0052710,2026-06-05 02:57:00+05:30,2026-06-09 08:52:00+05:30,Jaipur,JAI-03,CLINIC,APP,"{'patient_id': 'PJAI0028823', 'is_new': False}","[{'code': 'T002', 'price': 120}, {'code': 'T01...",0,NaN,booked
2,nova_jai_0052711,2026-06-11 07:55:00+05:30,2026-06-15 09:38:00+05:30,Jaipur,JAI-02,HOME,WALKIN,"{'patient_id': 'PJAI0026054', 'is_new': False}","[{'code': 'T004', 'price': 650}, {'code': 'T01...",150,NaN,booked
3,nova_jai_0052712,2026-06-27 09:28:00+05:30,2026-06-29 19:22:00+05:30,Jaipur,JAI-03,HOME,WALKIN,"{'patient_id': 'PJAI0027926', 'is_new': False}","[{'code': 'T007', 'price': 550}, {'code': 'T01...",150,NaN,booked
4,nova_jai_0052713,2026-06-20 09:50:00+05:30,2026-06-22 18:44:00+05:30,Jaipur,JAI-03,CLINIC,PHONE,"{'patient_id': 'PJAI0024547', 'is_new': False}","[{'code': 'T002', 'price': 120}]",0,NaN,booked

In [58]:
jaipur_nova_df[['patient_id', 'is_new']] = pd.DataFrame(jaipur_nova_df['patient'].tolist(), index=jaipur_nova_df.index)
jaipur_nova_df

,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient,tests,home_fee,rescheduled_from,status_at_export,patient_id,is_new
0,nova_jai_0052709,2026-06-26 03:04:00+05:30,2026-06-29 10:24:00+05:30,Jaipur,JAI-01,CLINIC,PHONE,"{'patient_id': 'PJAI0028832', 'is_new': False}","[{'code': 'T013', 'price': 400}, {'code': 'T00...",0,NaN,booked,PJAI0028832,False
1,nova_jai_0052710,2026-06-05 02:57:00+05:30,2026-06-09 08:52:00+05:30,Jaipur,JAI-03,CLINIC,APP,"{'patient_id': 'PJAI0028823', 'is_new': False}","[{'code': 'T002', 'price': 120}, {'code': 'T01...",0,NaN,booked,PJAI0028823,False
2,nova_jai_0052711,2026-06-11 07:55:00+05:30,2026-06-15 09:38:00+05:30,Jaipur,JAI-02,HOME,WALKIN,"{'patient_id': 'PJAI0026054', 'is_new': False}","[{'code': 'T004', 'price': 650}, {'code': 'T01...",150,NaN,booked,PJAI0026054,False
3,nova_jai_0052712,2026-06-27 09:28:00+05:30,2026-06-29 19:22:00+05:30,Jaipur,JAI-03,HOME,WALKIN,"{'patient_id': 'PJAI0027926', 'is_new': False}","[{'code': 'T007', 'price': 550}, {'code': 'T01...",150,NaN,booked,PJAI0027926,False
4,nova_jai_0052713,2026-06-20 09:50:00+05:30,2026-06-22 18:44:00+05:30,Jaipur,JAI-03,CLINIC,PHONE,"{'patient_id': 'PJAI0024547', 'is_new': False}","[{'code': 'T002', 'price': 120}]",0,NaN,booked,PJAI0024547,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8917,nova_jai_0052704,2026-05-04 10:06:00+05:30,2026-05-09 19:27:00+05:30,Jaipur,JAI-01,CLINIC,PHONE,"{'patient_id': 'PJAI0020725', 'is_new': False}","[{'code': 'T005', 'price': 700}, {'code': 'PK0...",0,nova_jai_0051374,booked,PJAI0020725,False
8918,nova_jai_0052705,2026-05-03 06:27:00+05:30,2026-05-05 12:22:00+05:30,Jaipur,JAI-04,HOME,WALKIN,"{'patient_id': 'PJAI0003149', 'is_new': False}","[{'code': 'T018', 'price': 700}, {'code': 'T00...",150,nova_jai_0050258,booked,PJAI0003149,False
8919,nova_jai_0052706,2026-05-18 03:22:00+05:30,2026-05-26 11:13:00+05:30,Jaipur,JAI-03,CLINIC,WALKIN,"{'patient_id': 'PJAI0027519', 'is_new': False}","[{'code': 'T007', 'price': 550}]",0,nova_jai_0051827,booked,PJAI0027519,False
8920,nova_jai_0052707,2026-05-18 08:37:00+05:30,2026-05-22 16:27:00+05:30,Jaipur,JAI-04,CLINIC,APP,"{'patient_id': 'PJAI0026829', 'is_new': False}","[{'code': 'PK03', 'price': 999}, {'code': 'T00...",0,nova_jai_0051100,booked,PJAI0026829,False
8921,nova_jai_0052708,2026-05-11 00:33:00+05:30,2026-05-15 10:23:00+05:30,Jaipur,JAI-01,HOME,PHONE,"{'patient_id': 'PJAI0028547', 'is_new': True}","[{'code': 'T004', 'price': 650}]",150,nova_jai_0052139,booked,PJAI0028547,True

In [59]:
tests_df = jaipur_nova_df.explode('tests', ignore_index=True)

In [60]:
tests_df

,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient,tests,home_fee,rescheduled_from,status_at_export,patient_id,is_new
0,nova_jai_0052709,2026-06-26 03:04:00+05:30,2026-06-29 10:24:00+05:30,Jaipur,JAI-01,CLINIC,PHONE,"{'patient_id': 'PJAI0028832', 'is_new': False}","{'code': 'T013', 'price': 400}",0,NaN,booked,PJAI0028832,False
1,nova_jai_0052709,2026-06-26 03:04:00+05:30,2026-06-29 10:24:00+05:30,Jaipur,JAI-01,CLINIC,PHONE,"{'patient_id': 'PJAI0028832', 'is_new': False}","{'code': 'T007', 'price': 550}",0,NaN,booked,PJAI0028832,False
2,nova_jai_0052710,2026-06-05 02:57:00+05:30,2026-06-09 08:52:00+05:30,Jaipur,JAI-03,CLINIC,APP,"{'patient_id': 'PJAI0028823', 'is_new': False}","{'code': 'T002', 'price': 120}",0,NaN,booked,PJAI0028823,False
3,nova_jai_0052710,2026-06-05 02:57:00+05:30,2026-06-09 08:52:00+05:30,Jaipur,JAI-03,CLINIC,APP,"{'patient_id': 'PJAI0028823', 'is_new': False}","{'code': 'T017', 'price': 450}",0,NaN,booked,PJAI0028823,False
4,nova_jai_0052711,2026-06-11 07:55:00+05:30,2026-06-15 09:38:00+05:30,Jaipur,JAI-02,HOME,WALKIN,"{'patient_id': 'PJAI0026054', 'is_new': False}","{'code': 'T004', 'price': 650}",150,NaN,booked,PJAI0026054,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21005,nova_jai_0052705,2026-05-03 06:27:00+05:30,2026-05-05 12:22:00+05:30,Jaipur,JAI-04,HOME,WALKIN,"{'patient_id': 'PJAI0003149', 'is_new': False}","{'code': 'T002', 'price': 120}",150,nova_jai_0050258,booked,PJAI0003149,False
21006,nova_jai_0052706,2026-05-18 03:22:00+05:30,2026-05-26 11:13:00+05:30,Jaipur,JAI-03,CLINIC,WALKIN,"{'patient_id': 'PJAI0027519', 'is_new': False}","{'code': 'T007', 'price': 550}",0,nova_jai_0051827,booked,PJAI0027519,False
21007,nova_jai_0052707,2026-05-18 08:37:00+05:30,2026-05-22 16:27:00+05:30,Jaipur,JAI-04,CLINIC,APP,"{'patient_id': 'PJAI0026829', 'is_new': False}","{'code': 'PK03', 'price': 999}",0,nova_jai_0051100,booked,PJAI0026829,False
21008,nova_jai_0052707,2026-05-18 08:37:00+05:30,2026-05-22 16:27:00+05:30,Jaipur,JAI-04,CLINIC,APP,"{'patient_id': 'PJAI0026829', 'is_new': False}","{'code': 'T001', 'price': 350}",0,nova_jai_0051100,booked,PJAI0026829,False
21009,nova_jai_0052708,2026-05-11 00:33:00+05:30,2026-05-15 10:23:00+05:30,Jaipur,JAI-01,HOME,PHONE,"{'patient_id': 'PJAI0028547', 'is_new': True}","{'code': 'T004', 'price': 650}",150,nova_jai_0052139,booked,PJAI0028547,True

In [61]:
detailed_tests = pd.json_normalize(tests_df['tests'])

In [62]:
detailed_tests.head()

   code  price
0  T013  400.0
1  T007  550.0
2  T002  120.0
3  T017  450.0
4  T004  650.0

In [63]:
tests_df = (
    tests_df
    .drop(columns='tests')
    .join(detailed_tests)
)

In [64]:
tests_df.head()

,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient,home_fee,rescheduled_from,status_at_export,patient_id,is_new,code,price
0,nova_jai_0052709,2026-06-26 03:04:00+05:30,2026-06-29 10:24:00+05:30,Jaipur,JAI-01,CLINIC,PHONE,"{'patient_id': 'PJAI0028832', 'is_new': False}",0,NaN,booked,PJAI0028832,False,T013,400.0
1,nova_jai_0052709,2026-06-26 03:04:00+05:30,2026-06-29 10:24:00+05:30,Jaipur,JAI-01,CLINIC,PHONE,"{'patient_id': 'PJAI0028832', 'is_new': False}",0,NaN,booked,PJAI0028832,False,T007,550.0
2,nova_jai_0052710,2026-06-05 02:57:00+05:30,2026-06-09 08:52:00+05:30,Jaipur,JAI-03,CLINIC,APP,"{'patient_id': 'PJAI0028823', 'is_new': False}",0,NaN,booked,PJAI0028823,False,T002,120.0
3,nova_jai_0052710,2026-06-05 02:57:00+05:30,2026-06-09 08:52:00+05:30,Jaipur,JAI-03,CLINIC,APP,"{'patient_id': 'PJAI0028823', 'is_new': False}",0,NaN,booked,PJAI0028823,False,T017,450.0
4,nova_jai_0052711,2026-06-11 07:55:00+05:30,2026-06-15 09:38:00+05:30,Jaipur,JAI-02,HOME,WALKIN,"{'patient_id': 'PJAI0026054', 'is_new': False}",150,NaN,booked,PJAI0026054,False,T004,650.0

In [65]:
tests_new = tests_new[['booking_id', 'created_at', 'slot_at', 'city', 'clinic_id', 'channel', 'source', 'patient_id','patient_name', 'test_code', 'test_price', 'home_fee']]

In [66]:
tests_new

,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee
0,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,PCHE0047415,Rohan Patel,T011,750.0,0
1,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,PCHE0047415,Rohan Patel,T012,600.0,0
2,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,PCHE0047415,Rohan Patel,PK04,2499.0,0
3,nova_che_0099368,2026-06-17 22:53:00+05:30,2026-06-21 08:23:00+05:30,Chennai,CHE-01,CLINIC,APP,PCHE0022985,Ananya Bose,T009,800.0,0
4,nova_che_0099369,2026-06-04 10:51:00+05:30,2026-06-06 12:34:00+05:30,Chennai,CHE-02,CLINIC,PHONE,PCHE0050893,Vihaan Menon,T014,150.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
62434,nova_jai_0052705,2026-05-03 06:27:00+05:30,2026-05-05 12:22:00+05:30,Jaipur,JAI-04,HOME,WALKIN,PJAI0003149,Ananya Fernandes,T002,120.0,150
62435,nova_jai_0052706,2026-05-18 03:22:00+05:30,2026-05-26 11:13:00+05:30,Jaipur,JAI-03,CLINIC,WALKIN,PJAI0027519,Nisha Gupta,T007,550.0,0
62436,nova_jai_0052707,2026-05-18 08:37:00+05:30,2026-05-22 16:27:00+05:30,Jaipur,JAI-04,CLINIC,APP,PJAI0026829,Neha Patel,PK03,999.0,0
62437,nova_jai_0052707,2026-05-18 08:37:00+05:30,2026-05-22 16:27:00+05:30,Jaipur,JAI-04,CLINIC,APP,PJAI0026829,Neha Patel,T001,350.0,0
62438,nova_jai_0052708,2026-05-11 00:33:00+05:30,2026-05-15 10:23:00+05:30,Jaipur,JAI-01,HOME,PHONE,PJAI0028547,Arjun Joshi,T004,650.0,150

In [67]:
tests_new.to_csv('jaipur_nova.csv', index = False)

In [68]:
df_chennai = pd.read_csv('chennai_nova.csv')

In [69]:
df_chennai.shape

(62439, 12)

In [70]:
df_jaipur = pd.read_csv('jaipur_nova.csv')

In [71]:
df_jaipur.shape

(62439, 12)

In [72]:
df_new = pd.concat([df_chennai, df_jaipur], ignore_index=True)

In [73]:
df_new

,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee
0,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,PCHE0047415,Rohan Patel,T011,750.0,0
1,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,PCHE0047415,Rohan Patel,T012,600.0,0
2,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,PCHE0047415,Rohan Patel,PK04,2499.0,0
3,nova_che_0099368,2026-06-17 22:53:00+05:30,2026-06-21 08:23:00+05:30,Chennai,CHE-01,CLINIC,APP,PCHE0022985,Ananya Bose,T009,800.0,0
4,nova_che_0099369,2026-06-04 10:51:00+05:30,2026-06-06 12:34:00+05:30,Chennai,CHE-02,CLINIC,PHONE,PCHE0050893,Vihaan Menon,T014,150.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
124873,nova_jai_0052705,2026-05-03 06:27:00+05:30,2026-05-05 12:22:00+05:30,Jaipur,JAI-04,HOME,WALKIN,PJAI0003149,Ananya Fernandes,T002,120.0,150
124874,nova_jai_0052706,2026-05-18 03:22:00+05:30,2026-05-26 11:13:00+05:30,Jaipur,JAI-03,CLINIC,WALKIN,PJAI0027519,Nisha Gupta,T007,550.0,0
124875,nova_jai_0052707,2026-05-18 08:37:00+05:30,2026-05-22 16:27:00+05:30,Jaipur,JAI-04,CLINIC,APP,PJAI0026829,Neha Patel,PK03,999.0,0
124876,nova_jai_0052707,2026-05-18 08:37:00+05:30,2026-05-22 16:27:00+05:30,Jaipur,JAI-04,CLINIC,APP,PJAI0026829,Neha Patel,T001,350.0,0
124877,nova_jai_0052708,2026-05-11 00:33:00+05:30,2026-05-15 10:23:00+05:30,Jaipur,JAI-01,HOME,PHONE,PJAI0028547,Arjun Joshi,T004,650.0,150

In [74]:
df_all_cities_master = pd.read_csv('/Users/dhairyajoshi/Public/iitgn assignments/Assignment 1 Kalpa- Healthcare/Week_3_Build_Week_Kalpa_Heath_Project/merged_csv/all_cities_master.csv')

/var/folders/mm/n0h6pkc95kg2vxx3h1jwql800000gn/T/ipykernel_86981/2497762708.py:1: DtypeWarning: Columns (10: test_price, 11: home_fee) have mixed types. Specify dtype option on import or set low_memory=False.
  df_all_cities_master = pd.read_csv('/Users/dhairyajoshi/Public/iitgn assignments/Assignment 1 Kalpa- Healthcare/Week_3_Build_Week_Kalpa_Heath_Project/merged_csv/all_cities_master.csv')

In [75]:
df_final = pd.concat([df_new , df_all_cities_master], ignore_index=True)

In [76]:
df_final.head(50)

,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee,source_city,source_file
0,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,PCHE0047415,Rohan Patel,T011,750.0,0,NaN,NaN
1,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,PCHE0047415,Rohan Patel,T012,600.0,0,NaN,NaN
2,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,PCHE0047415,Rohan Patel,PK04,2499.0,0,NaN,NaN
3,nova_che_0099368,2026-06-17 22:53:00+05:30,2026-06-21 08:23:00+05:30,Chennai,CHE-01,CLINIC,APP,PCHE0022985,Ananya Bose,T009,800.0,0,NaN,NaN
4,nova_che_0099369,2026-06-04 10:51:00+05:30,2026-06-06 12:34:00+05:30,Chennai,CHE-02,CLINIC,PHONE,PCHE0050893,Vihaan Menon,T014,150.0,0,NaN,NaN
5,nova_che_0099369,2026-06-04 10:51:00+05:30,2026-06-06 12:34:00+05:30,Chennai,CHE-02,CLINIC,PHONE,PCHE0050893,Vihaan Menon,T001,350.0,0,NaN,NaN
6,nova_che_0099369,2026-06-04 10:51:00+05:30,2026-06-06 12:34:00+05:30,Chennai,CHE-02,CLINIC,PHONE,PCHE0050893,Vihaan Menon,T002,120.0,0,NaN,NaN
7,nova_che_0099370,2026-06-26 07:04:00+05:30,2026-06-28 10:53:00+05:30,Chennai,CHE-02,HOME,PHONE,PCHE0048337,Diya Iyer,PK01,1499.0,150,NaN,NaN
8,nova_che_0099370,2026-06-26 07:04:00+05:30,2026-06-28 10:53:00+05:30,Chennai,CHE-02,HOME,PHONE,PCHE0048337,Diya Iyer,PK04,2499.0,150,NaN,NaN
9,nova_che_0099371,2026-06-06 00:56:00+05:30,2026-06-07 06:44:00+05:30,Chennai,CHE-04,CLINIC,APP,PCHE0047986,Varun Kulkarni,T008,1100.0,0,NaN,NaN
10,nova_che_0099371,2026-06-06 00:56:00+05:30,2026-06-07 06:44:00+05:30,Chennai,CHE-04,CLINIC,APP,PCHE0047986,Varun Kulkarni,T003,450.0,0,NaN,NaN
11,nova_che_0099371,2026-06-06 00:56:00+05:30,2026-06-07 06:44:00+05:30,Chennai,CHE-04,CLINIC,APP,PCHE0047986,Varun Kulkarni,T001,350.0,0,NaN,NaN
12,nova_che_0099372,2026-06-05 08:34:00+05:30,2026-06-07 12:55:00+05:30,Chennai,CHE-01,HOME,PHONE,PCHE0044666,Priya Desai,T002,120.0,150,NaN,NaN
13,nova_che_0099373,2026-06-14 15:44:00+05:30,2026-06-15 18:51:00+05:30,Chennai,CHE-03,HOME,PHONE,PCHE0022826,Varun Joshi,T001,350.0,150,NaN,NaN
14,nova_che_0099373,2026-06-14 15:44:00+05:30,2026-06-15 18:51:00+05:30,Chennai,CHE-03,HOME,PHONE,PCHE0022826,Varun Joshi,T007,550.0,150,NaN,NaN
15,nova_che_0099373,2026-06-14 15:44:00+05:30,2026-06-15 18:51:00+05:30,Chennai,CHE-03,HOME,PHONE,PCHE0022826,Varun Joshi,T002,120.0,150,NaN,NaN
16,nova_che_0099374,2026-06-02 10:01:00+05:30,2026-06-03 17:54:00+05:30,Chennai,CHE-03,CLINIC,APP,PCHE0047256,Mary Patel,T005,700.0,0,NaN,NaN
17,nova_che_0099374,2026-06-02 10:01:00+05:30,2026-06-03 17:54:00+05:30,Chennai,CHE-03,CLINIC,APP,PCHE0047256,Mary Patel,T010,150.0,0,NaN,NaN
18,nova_che_0099375,2026-06-16 23:33:00+05:30,2026-06-17 08:01:00+05:30,Chennai,CHE-04,CLINIC,APP,PCHE0038916,Renée Nair,T004,650.0,0,NaN,NaN
19,nova_che_0099376,2026-06-28 09:51:00+05:30,2026-06-30 12:48:00+05:30,Chennai,CHE-05,HOME,APP,PCHE0051335,Aditi Khan,T001,350.0,150,NaN,NaN
20,nova_che_0099376,2026-06-28 09:51:00+05:30,2026-06-30 12:48:00+05:30,Chennai,CHE-05,HOME,APP,PCHE0051335,Aditi Khan,T003,450.0,150,NaN,NaN
21,nova_che_0099376,2026-06-28 09:51:00+05:30,2026-06-30 12:48:00+05:30,Chennai,CHE-05,HOME,APP,PCHE0051335,Aditi Khan,T010,150.0,150,NaN,NaN
22,nova_che_0099376,2026-06-28 09:51:00+05:30,2026-06-30 12:48:00+05:30,Chennai,CHE-05,HOME,APP,PCHE0051335,Aditi Khan,T002,120.0,150,NaN,NaN
23,nova_che_0099377,2026-06-19 06:48:00+05:30,2026-06-23 11:22:00+05:30,Chennai,CHE-03,HOME,PHONE,PCHE0053088,Zoya D'Souza,T003,450.0,150,NaN,NaN
24,nova_che_0099377,2026-06-19 06:48:00+05:30,2026-06-23 11:22:00+05:30,Chennai,CHE-03,HOME,PHONE,PCHE0053088,Zoya D'Souza,T011,750.0,150,NaN,NaN
25,nova_che_0099378,2026-06-09 12:01:00+05:30,2026-06-13 18:24:00+05:30,Chennai,CHE-03,HOME,PHONE,PCHE0046777,Meera Patel,T002,120.0,150,NaN,NaN
26,nova_che_0099378,2026-06-09 12:01:00+05:30,2026-06-13 18:24:00+05:30,Chennai,CHE-03,HOME,PHONE,PCHE0046777,Meera Patel,T004,650.0,150,NaN,NaN
27,nova_che_0099378,2026-06-09 12:01:00+05:30,2026-06-13 18:24:00+05:30,Chennai,CHE-03,HOME,PHONE,PCHE0046777,Meera Patel,T001,350.0,150,NaN,NaN
28,nova_che_0099378,2026-06-09 12:01:00+05:30,2026-06-13 18:24:00+05:30,Chennai,CHE-03,HOME,PHONE,PCHE0046777,Meera Patel,PK03,999.0,150,NaN,NaN
29,nova_che_0099379,2026-06-22 04:16:00+05:30,2026-06-23 09:36:00+05:30,Chennai,CHE-01,CLINIC,APP,PCHE0047254,Neha Fernandes,T002,120.0,0,NaN,NaN
30,nova_che_0099379,2026-06-22 04:16:00+05:30,2026-06-23 09:36:00+05:30,Chennai,CHE-01,CLINIC,APP,PCHE0047254,Neha Fernandes,T003,450.0,0,NaN,NaN
31,nova_che_0099380,2026-06-09 22:58:00+05:30,2026-06-10 08:36:00+05:30,Chennai,CHE-05,HOME,PHONE,PCHE0039515,Zoya Shah,T020,450.0,150,NaN,NaN
32,nova_che_0099380,2026-06-09 22:58:00+05:30,2026-06-10 08:36:00+05:30,Chennai,CHE-05,HOME,PHONE,PCHE0039515,Zoya Shah,T003,450.0,150,NaN,NaN
33,nova_che_0099381,2026-06-03 21:50:00+05:30,2026-06-04 06:20:00+05:30,Chennai,CHE-02,CLINIC,PHONE,PCHE0050075,Arjun Fernandes,T015,180.0,0,NaN,NaN
34,nova_che_0099381,2026-06-03 21:50:00+05:30,2026-06-04 06:20:00+05:30,Chennai,CHE-02,CLINIC,PHONE,PCHE0050075,Arjun Fernandes,T011,750.0,0,NaN,NaN
35,nova_che_0099381,2026-06-03 21:50:00+05:30,2026-06-04 06:20:00+05:30,Chennai,CHE-02,CLINIC,PHONE,PCHE0050075,Arjun Fernandes,T007,550.0,0,NaN,NaN
36,nova_che_0099382,2026-06-18 00:19:00+05:30,2026-06-19 06:35:00+05:30,Chennai,CHE-05,HOME,APP,PCHE0047842,Varun Mehta,T002,120.0,150,NaN,NaN
37,nova_che_0099382,2026-06-18 00:19:00+05:30,2026-06-19 06:35:00+05:30,Chennai,CHE-05,HOME,APP,PCHE0047842,Varun Mehta,PK01,1499.0,150,NaN,NaN
38,nova_che_0099382,2026-06-18 00:19:00+05:30,2026-06-19 06:35:00+05:30,Chennai,CHE-05,HOME,APP,PCHE0047842,Varun Mehta,T016,160.0,150,NaN,NaN
39,nova_che_0099383,2026-06-04 06:51:00+05:30,2026-06-08 10:31:00+05:30,Chennai,CHE-01,CLINIC,PHONE,PCHE0012512,José Gupta,PK01,1499.0,0,NaN,NaN
40,nova_che_0099384,2026-06-10 11:42:00+05:30,2026-06-11 12:00:00+05:30,Chennai,CHE-01,CLINIC,APP,PCHE0054080,Rohan Sharma,T002,120.0,0,NaN,NaN
41,nova_che_0099384,2026-06-10 11:42:00+05:30,2026-06-11 12:00:00+05:30,Chennai,CHE-01,CLINIC,APP,PCHE0054080,Rohan Sharma,T011,750.0,0,NaN,NaN
42,nova_che_0099384,2026-06-10 11:42:00+05:30,2026-06-11 12:00:00+05:30,Chennai,CHE-01,CLINIC,APP,PCHE0054080,Rohan Sharma,T003,450.0,0,NaN,NaN
43,nova_che_0099385,2026-06-11 05:47:00+05:30,2026-06-13 06:07:00+05:30,Chennai,CHE-01,CLINIC,APP,PCHE0049360,Zoya Naidu,T002,120.0,0,NaN,NaN
44,nova_che_0099385,2026-06-11 05:47:00+05:30,2026-06-13 06:07:00+05:30,Chennai,CHE-01,CLINIC,APP,PCHE0049360,Zoya Naidu,T003,450.0,0,NaN,NaN
45,nova_che_0099386,2026-06-15 08:29:00+05:30,2026-06-16 10:36:00+05:30,Chennai,CHE-04,CLINIC,PHONE,PCHE0045975,Manish Pillai,T003,450.0,0,NaN,NaN
46,nova_che_0099386,2026-06-15 08:29:00+05:30,2026-06-16 10:36:00+05:30,Chennai,CHE-04,CLINIC,PHONE,PCHE0045975,Manish Pillai,T001,350.0,0,NaN,NaN
47,nova_che_0099387,2026-06-11 16:48:00+05:30,2026-06-16 17:26:00+05:30,Chennai,CHE-04,HOME,PHONE,PCHE0047842,Varun Mehta,T008,1100.0,150,NaN,NaN
48,nova_che_0099387,2026-06-11 16:48:00+05:30,2026-06-16 17:26:00+05:30,Chennai,CHE-04,HOME,PHONE,PCHE0047842,Varun Mehta,T004,650.0,150,NaN,NaN
49,nova_che_0099387,2026-06-11 16:48:00+05:30,2026-06-16 17:26:00+05:30,Chennai,CHE-04,HOME,PHONE,PCHE0047842,Varun Mehta,T001,350.0,150,NaN,NaN

In [77]:
df_final.shape

(1377664, 14)

In [78]:
df_final["city"].unique()

<StringArray>
[  'Chennai',    'Jaipur', 'Ahmedabad',      'city', 'Bangalore', 'Bengaluru',
 'Hyderabad',      'Pune']
Length: 8, dtype: str

In [79]:
df_final["city"].value_counts()

city
Chennai      284975
Ahmedabad    235373
Hyderabad    220989
Bangalore    193558
Pune         185149
Jaipur       149938
Bengaluru    107661
city             21
Name: count, dtype: int64

In [82]:
df_final.drop(["city"] , axis=1, inplace=True)

/var/folders/mm/n0h6pkc95kg2vxx3h1jwql800000gn/T/ipykernel_86981/1081465249.py:1: Pandas4Warning: The inplace keyword in DataFrame.drop is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  df_final.drop(["city"] , axis=1, inplace=True)

In [83]:
df_final["city"].unique()

KeyError: 'city'

In [80]:
df_final[df_final["city"] == "city"]

,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee,source_city,source_file
353113,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee,ahmedabad,bookings_2026-06.csv
531656,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee,bengaluru,bookings_2025-11.csv
562893,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee,bengaluru,bookings_2026-01.csv
617889,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee,bengaluru,bookings_2026-04.csv
653009,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee,bengaluru,bookings_2026-06.csv
708405,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee,chennai,bookings_2025-04.csv
775239,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee,chennai,bookings_2025-09.csv
815313,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee,chennai,bookings_2025-12.csv
828709,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee,chennai,bookings_2026-01.csv
894719,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee,hyderabad,bookings_2025-03.csv
907049,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee,hyderabad,bookings_2025-04.csv
919298,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee,hyderabad,bookings_2025-05.csv
931033,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee,hyderabad,bookings_2025-06.csv
1012513,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee,hyderabad,bookings_2026-01.csv
1025909,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee,hyderabad,bookings_2026-02.csv
1096261,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee,jaipur,bookings_2025-02.csv
1168618,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee,jaipur,bookings_2025-12.csv
1208082,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee,pune,bookings_2025-02.csv
1258131,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee,pune,bookings_2025-07.csv
1287831,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee,pune,bookings_2025-10.csv
1329026,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee,pune,bookings_2026-02.csv

In [81]:
df_final.head()

,booking_id,created_at,slot_at,city,clinic_id,channel,source,patient_id,patient_name,test_code,test_price,home_fee,source_city,source_file
0,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,PCHE0047415,Rohan Patel,T011,750.0,0,NaN,NaN
1,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,PCHE0047415,Rohan Patel,T012,600.0,0,NaN,NaN
2,nova_che_0099367,2026-05-27 15:30:00+05:30,2026-06-01 18:15:00+05:30,Chennai,CHE-05,CLINIC,APP,PCHE0047415,Rohan Patel,PK04,2499.0,0,NaN,NaN
3,nova_che_0099368,2026-06-17 22:53:00+05:30,2026-06-21 08:23:00+05:30,Chennai,CHE-01,CLINIC,APP,PCHE0022985,Ananya Bose,T009,800.0,0,NaN,NaN
4,nova_che_0099369,2026-06-04 10:51:00+05:30,2026-06-06 12:34:00+05:30,Chennai,CHE-02,CLINIC,PHONE,PCHE0050893,Vihaan Menon,T014,150.0,0,NaN,NaN